name: Continuous Integration
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
    - run: npm install
    - run: npm test
      env:
        CI: true
